### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by acosonic** [dreamyguy/gitinsight#1]
Hi, where do I tell it which logs to monitor?

**Comment by dreamyguy** [comment]
Hey @acosonic, it has been a long time but hopefully I have good news!

I've enriched the application quite a bit since you posted this (very 1st!) issue, especially in the last few days. I've taken the time to document the requirements as much as possible, while simplifying the whole flow.

Have a look at both [getting started](https://github.com/dreamyguy/gitinsight#getting-started) and [running it](https://github.com/dreamyguy/gitinsight#running-it) sections on the README.

It might seem like a lot to get through to fire-up the application, but that's just me elaborating on each step.

Thank you for pointing this out! 🙌  It helped me realise that my instructions - _and the application itself_ - needed simplification...
